<?php

/*
 * Task runner, code generator and build tool for easier continuos integration
 *
 * @link      https://github.com/hiqdev/hidev
 * @package   hidev
 * @license   BSD-3-Clause
 * @copyright Copyright (c) 2014-2015, HiQDev (http://hiqdev.com/)
 */

namespace hidev\tests\unit\goals;

use hidev\goals\FileGoal;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-23 at 14:03:00.
 */
class FileGoalTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FileGoal
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FileGoal('test', null);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers hidev\goals\FileGoal::setTemplate
     *
     * @todo   Implement testSetTemplate().
     */
    public function testSetTemplate()
    {
        $this->assertFalse(false);
    }

    /**
     * @covers hidev\goals\FileGoal::getTemplate
     *
     * @todo   Implement testGetTemplate().
     */
    public function testGetTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hidev\goals\FileGoal::getFile
     *
     * @todo   Implement testGetFile().
     */
    public function testGetFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hidev\goals\FileGoal::setFile
     *
     * @todo   Implement testSetFile().
     */
    public function testSetFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hidev\goals\FileGoal::getDirname
     *
     * @todo   Implement testGetDirname().
     */
    public function testGetDirname()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hidev\goals\FileGoal::getPath
     *
     * @todo   Implement testGetPath().
     */
    public function testGetPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hidev\goals\FileGoal::exists
     *
     * @todo   Implement testExists().
     */
    public function testExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hidev\goals\FileGoal::read
     *
     * @todo   Implement testRead().
     */
    public function testRead()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hidev\goals\FileGoal::readArray
     *
     * @todo   Implement testReadArray().
     */
    public function testReadArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hidev\goals\FileGoal::actionLoad
     *
     * @todo   Implement testActionLoad().
     */
    public function testActionLoad()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hidev\goals\FileGoal::actionSave
     *
     * @todo   Implement testActionSave().
     */
    public function testActionSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
